-- 프로그래머스 - ROOT 아이템 구하기(Lv.2)
SELECT ITEM_INFO.ITEM_ID as ITEM_ID, ITEM_INFO.ITEM_NAME as ITEM_NAME
FROM ITEM_INFO, ITEM_TREE
WHERE ITEM_INFO.ITEM_ID = ITEM_TREE.ITEM_ID
    AND PARENT_ITEM_ID IS NULL
ORDER BY ITEM_INFO.ITEM_ID;