-- 프로그래머스 - FrontEnd 개발자 찾기(Lv.4)
WITH FRONT_END
  AS (SELECT SUM(CODE) as CODE
      FROM SKILLCODES 
      WHERE CATEGORY LIKE 'Front End')

SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS, FRONT_END
WHERE SKILL_CODE & FRONT_END.CODE
ORDER BY ID;