-- 프로그래머스 - 부모의 형질을 모두 가지는 대장균 찾기(Lv.2)
SELECT CHILD.ID as ID, CHILD.GENOTYPE as GENOTYPE, PARENT.GENOTYPE as PARENT_GENOTYPE
FROM ECOLI_DATA as CHILD
  JOIN ECOLI_DATA as PARENT
  ON CHILD.PARENT_ID = PARENT.ID
WHERE CHILD.GENOTYPE & PARENT.GENOTYPE = PARENT.GENOTYPE
ORDER BY CHILD.ID;