-- SUM, MAX, MIN: 연도별 대장균 크기의 편차 구하기(Lv.2)
WITH MAX_SIZE AS (
  SELECT MAX(SIZE_OF_COLONY) as MaxSize, YEAR(DIFFERENTIATION_DATE) as YEAR
  FROM ECOLI_DATA
  GROUP BY YEAR
)

SELECT YEAR(DIFFERENTIATION_DATE) as YEAR, (MaxSize - SIZE_OF_COLONY) as YEAR_DEV, ID
FROM ECOLI_DATA, MAX_SIZE
WHERE YEAR(DIFFERENTIATION_DATE) = MAX_SIZE.YEAR
ORDER BY YEAR, YEAR_DEV;